services:
  elastic:
    container_name: elastic
    hostname: elastic
    image: elasticsearch:9.1.0
    environment:
    - node.name=elastic
    - discovery.type=single-node
    - http.host=0.0.0.0
    - http.cors.enabled=true
    - http.cors.allow-origin="*"
    - xpack.security.enabled=false
    - xpack.security.enrollment.enabled=false
    - xpack.security.http.ssl.enabled=false
    restart: unless-stopped
    ports:
    - 9200:9200
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
